### PR TITLE
cherry pick master

### PR DESCRIPTION
**Pull request by ReyDonovan**
7.3.5 branch update

### CODE REVIEW

**Comment by Aokromes** [comment]
you are sure you targeted the correct repo and branch?

**Comment by ReyDonovan** [comment]
yes, I am sure. If I'm not mistaken then this is a legacy) it's just a continuation of legion branch support

**Comment by Aokromes** [comment]
well, it was intended archive branch xd

**Comment by ReyDonovan** [comment]
OK I understood

**Pull request closed without merging**
